---

- hosts: 127.0.0.1
  connection: local

  tasks:


  - name: update scripts
    copy:
      src: "{{ item }}"
      dest: /usr/local/sbin/
      mode: 0755  
      owner: root
      group: root
    with_fileglob:
      - "/usr/local/src/lab-on-an-ssd/playbooks/scripts/*"

