#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
/usr/bin/ansible-pull -U https://github.com/artic-network/fieldbioinformatics.git -d /usr/local/src/artic lab-on-an-ssd/playbooks/artic-disable-gpu-basecalling.yml

