#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
/usr/bin/ansible-pull -U https://github.com/artic-network/lab-on-an-SSD.git -d /usr/local/src/lab-on-an-ssd playbooks/updater.yml

